classdef programSettings
    properties
        mju;
        rMin;
        rMax;
        a_initial;
        a_final;
        omega1;
        omega2;
        e1;
        e2;
        Tp1;
        Tp2;
        n1;
        n2;
        P1;
        P2;
        p1;
        p2;
        intApprox;
        plotAccuracy;
        theta_0;
        safeTransferAngleMultiplier;
        TOF_corrMult;
        dAdjustment;
        opt_nu_fzero;
        opt_tf_angle;
        opt_tof_fzero;
        opt_d_lim_fzero;
        opt_minTheta_fbnd;
        solveDate;
        plotTransferWindow;
        useMultiorbitFilling;
        tfWindowPixelsX;
        tfWindowPixelsY;
    end
end

